package com.galegando21.utils

object SharedPreferencesKeys {
    const val ONBOARDING = "onboarding"
    const val IS_ONBOARDING_COMPLETED = "is_onboarding_completed"
    const val NOME = "name"
    const val PALABRAS_BASICAS_SOURCE = "palabras_basicas_source"
    const val DICTIONARY_SOURCE = "dictionary_source"
    const val APP_PREFERENCES = "app_preferences"
    const val HAS_USER_DENIED_PERMISSIONS_BEFORE = "hasUserDeniedPermissionBefore"
    const val UNLOCKED_BUTTONS = "BotonesDesbloqueados"
    const val UNLOCKED_BUTTON_COUNT = "unlockedButtonCount"
    const val STATISTICS = "statistics"
    const val CURRENT_STREAK = "current_streak"
    const val LONGEST_STREAK = "longest_streak"
    const val LAST_DAY_CURRENT_STREAK_UPDATED = "last_day_current_streak_updated"
    const val LAST_YEAR_CURRENT_STREAK_UPDATED = "last_year_current_streak_updated"
    const val PASAGALEGO_CORRECT_ANSWERS_DICTIONARY_EASY = "pasagalego_correct_answers_dictionary_easy"
    const val PASAGALEGO_ERROR_ANSWERS_DICTIONARY_EASY = "pasagalego_error_answers_dictionary_easy"
    const val PASAGALEGO_TIME_DICTIONARY_EASY = "pasagalego_time_dictionary_easy"
    const val PASAGALEGO_CORRECT_ANSWERS_DICTIONARY = "pasagalego_correct_answers_dictionary"
    const val PASAGALEGO_ERROR_ANSWERS_DICTIONARY = "pasagalego_error_answers_dictionary"
    const val PASAGALEGO_TIME_DICTIONARY = "pasagalego_time_dictionary"
    const val PASAGALEGO_CORRECT_ANSWERS_ORIXINAL = "pasagalego_correct_answers_orixinal"
    const val PASAGALEGO_ERROR_ANSWERS_ORIXINAL = "pasagalego_error_answers_orixinal"
    const val PASAGALEGO_TIME_ORIXINAL = "pasagalego_time_orixinal"
    const val ATRAPAME_SE_PODES_QUESTIONS_NEEDED = "atrapame_se_podes_questions_needed"
    const val ATRAPA_UN_MILLON_MAX_CASH = "atrapa_un_millon_max_cash"
    const val AFORCADO_MAX_STREAK_EASY = "aforcado_max_streak_easy"
    const val AFORCADO_MAX_STREAK_DIFICULT = "aforcado_max_streak_dificult"
    const val VERDADE_OU_MENTIRA_MAX_SCORE = "verdade_ou_mentira_max_score"
    const val ADIVINHA_ESCUDO_MAX_SCORE = "adivinha_escudo_max_score"
    const val ADIVINHA_ANO_FOTO_MAX_SCORE = "adivinha_ano_foto_max_score"
    const val AGORA_CAIGO_MAX_SCORE = "agora_caigo_max_score"
    const val PROBA_VELOCIDADE_MIN_TIME = "proba_velocidade_min_time"
    const val RULETA_DA_SORTE_MAX_CASH = "ruleta_da_sorte_max_cash"
    const val ONDE_ESTAN_MIN_TIME = "onde_estan_min_time"
    const val SOPA_LETRAS_MAX_SCORE = "sopa_letras_max_score"
    const val ANAGRAMAS_MAX_SCORE_EASY = "anagramas_max_score_easy"
    const val ANAGRAMAS_MAX_SCORE_DIFICULT = "anagramas_max_score_dificult"
    const val ADIVINHA_PERSONAXE_MAX_SCORE = "adivinha_personaxe_max_score"
    const val XOGO_PALABRAS_MAX_SCORE = "PUNTUACION_MAXIMA_XOGO_PALABRAS"
    const val EXPLOSION_PALABRAS_MAX_SCORE_EASY = "explosion_palabras_max_score_easy"
    const val EXPLOSION_PALABRAS_MAX_SCORE_DIFICULT = "explosion_palabras_max_score_dificult"
    const val WORDLE_MAX_STREAK = "wordle_max_streak"
    const val CONEXIONS_MAX_SCORE = "conexions_max_score"
}