package com.galegando21.utils

import com.galegando21.model.QuestionVerdadeOuMentira

object VerdadeOuMentiraConstants {

    const val SCORE = "correct_answers_verdade_ou_mentira"

    fun getQuestions(): MutableList<QuestionVerdadeOuMentira> {
        val questions = mutableListOf<QuestionVerdadeOuMentira>()
        questions.add(QuestionVerdadeOuMentira("Ibai Llanos ofreceulle a Marcial Mouzo retransmitir o seu programa nocturno co nome 'Pensando en Twitch'", 0))
        questions.add(QuestionVerdadeOuMentira("Elon Musk é o fundador da empresa SpaceX", 1))
        questions.add(QuestionVerdadeOuMentira("A Grande Muralha da China é visível dende o espazo", 0))
        questions.add(QuestionVerdadeOuMentira("A Mona Lisa é unha das pinturas máis famosas de Leonardo da Vinci", 1))
        questions.add(QuestionVerdadeOuMentira("A temperatura de conxelación da auga é de 100 graos Celsius", 0))
        questions.add(QuestionVerdadeOuMentira("A cidade de Nova York é a capital dos Estados Unidos da América", 0))
        questions.add(QuestionVerdadeOuMentira("O Sol é unha estrela", 1))
        questions.add(QuestionVerdadeOuMentira("A película \"Forrest Gump\" protagonizada por Tom Hanks gañou seis premios Óscar.", 1))
        questions.add(QuestionVerdadeOuMentira("A lúa orbita arredor da Terra.", 1))
        questions.add(QuestionVerdadeOuMentira("A pirámide de Khufu, tamén coñecida como a Gran Pirámide, é a máis grande das pirámides de Exipto.", 1))
        questions.add(QuestionVerdadeOuMentira("O río Amazonas é o máis longo do mundo.", 1))
        questions.add(QuestionVerdadeOuMentira("O chocolate é tóxico para os cans.", 1))
        questions.add(QuestionVerdadeOuMentira("O planeta máis grande do sistema solar é Xúpiter.", 1))
        questions.add(QuestionVerdadeOuMentira("O oso panda é nativo de China.", 1))
        questions.add(QuestionVerdadeOuMentira("O Titanic afundiu no ano 1912.", 1))
        questions.add(QuestionVerdadeOuMentira("A Mona Lisa foi pintada por Michelangelo.", 0))
        questions.add(QuestionVerdadeOuMentira("O fútbol é o deporte máis popular do mundo.", 1))
        questions.add(QuestionVerdadeOuMentira("A linguaxe de programación Python foi nomeada en honra á serie de televisión \"Monty Python's Flying Circus\".", 1))
        questions.add(QuestionVerdadeOuMentira("O volcán máis alto do mundo é o Ojos del Salado, situado en Chile.", 0))
        questions.add(QuestionVerdadeOuMentira("O 1 de abril é o Día dos Inocentes.", 0))
        questions.add(QuestionVerdadeOuMentira("A Coca-Cola foi creada accidentalmente por un farmacéutico.", 1))
        questions.add(QuestionVerdadeOuMentira("O Papa Francisco é o primeiro Papa latinoamericano da historia.", 1))
        questions.add(QuestionVerdadeOuMentira("A Torre Eiffel foi construída por Gustave Eiffel para a Exposición Universal de 1889 en París.", 1))
        questions.add(QuestionVerdadeOuMentira("O átomo é a unidade fundamental da materia que consta dun núcleo central e unha nube de electróns ao seu redor.", 1))
        questions.add(QuestionVerdadeOuMentira("A Mona Lisa está exposta no Museo do Louvre, en París.", 1))
        questions.add(QuestionVerdadeOuMentira("O planeta Marte ten dúas lúas chamadas Fobos e Deimos.", 1))
        questions.add(QuestionVerdadeOuMentira("O monte Everest é a montaña máis alta do mundo sobre o nivel do mar.", 1))
        questions.add(QuestionVerdadeOuMentira("O primeiro ser humano en pisar a Lúa foi Neil Armstrong.", 1))
        questions.add(QuestionVerdadeOuMentira("O pingüino é unha ave que non voa.", 1))
        questions.add(QuestionVerdadeOuMentira("O idioma máis falado do mundo é o inglés.", 0))
        questions.add(QuestionVerdadeOuMentira("O símbolo químico do ouro na táboa periódica é 'Au'.", 1))
        questions.add(QuestionVerdadeOuMentira("O polo norte magnético da Terra está situado nunha localización fixa.", 0))
        questions.add(QuestionVerdadeOuMentira("O pintor español Pablo Picasso é coñecido pola súa contribución ao movemento cubista.", 1))
        questions.add(QuestionVerdadeOuMentira("A Gran Esfinxe de Exipto ten un corpo de león e unha cabeza humana.", 1))
        questions.add(QuestionVerdadeOuMentira("O deserto do Sahara é o deserto máis grande do mundo.", 1))
        questions.add(QuestionVerdadeOuMentira("A capital de Italia é Roma.", 1))
        questions.add(QuestionVerdadeOuMentira("O Presidente dos Estados Unidos pode servir un máximo de dous mandatos de catro anos cada un.", 1))
        questions.add(QuestionVerdadeOuMentira("A velocidade da luz é aproximadamente 300.000 quilómetros por segundo.", 1))
        questions.add(QuestionVerdadeOuMentira("O número pi é un número irracional que representa a relación entre a circunferencia dun círculo e o seu diámetro.", 1))
        questions.add(QuestionVerdadeOuMentira("O elemento químico californio foi descuberto en California.", 1))
        questions.add(QuestionVerdadeOuMentira("O Taj Mahal está situado na cidade de Nova Delhi, na India.", 0))
        questions.add(QuestionVerdadeOuMentira("O Buda histórico naceu na India.", 1))
        questions.add(QuestionVerdadeOuMentira("O pensador filosófico Friedrich Nietzsche escribiu en alemán.", 1))
        questions.add(QuestionVerdadeOuMentira("O río Nilo é o río máis longo do mundo.", 0))
        questions.add(QuestionVerdadeOuMentira("O composto químico H2O é coñecido como óxido de hidróxeno.", 0))
        questions.add(QuestionVerdadeOuMentira("O Monte Rushmore está situado no estado de Dakota do Sur, nos Estados Unidos.", 1))
        questions.add(QuestionVerdadeOuMentira("A Estatua da Liberdade foi un regalo de Francia aos Estados Unidos.", 1))
        questions.add(QuestionVerdadeOuMentira("O filósofo grego Sócrates escribiu numerosas obras que sobreviviron ata a actualidade.", 0))
        questions.add(QuestionVerdadeOuMentira("A Guerra dos Cen Anos durou exactamente 100 anos.", 0))
        questions.add(QuestionVerdadeOuMentira("O libro '1984', escrito por George Orwell, describe unha sociedade totalitaria e autoritaria.", 1))
        questions.add(QuestionVerdadeOuMentira("O poema épico 'A Odisea' foi escrito polo poeta grego Homero.", 1))
        questions.add(QuestionVerdadeOuMentira("O monte Kilimanjaro é a montaña máis alta de África.", 1))
        questions.add(QuestionVerdadeOuMentira("A película 'El Padrino' foi dirixido por Martin Scorsese.", 0))
        questions.add(QuestionVerdadeOuMentira("O cabalo é un mamífero ovíparo.", 0))
        questions.add(QuestionVerdadeOuMentira("O explorador portugués Vasco de Gama foi o primeiro europeo en chegar a India por mar.", 1))
        questions.add(QuestionVerdadeOuMentira("A teoría da relatividade foi formulada por Albert Einstein.", 1))
        questions.add(QuestionVerdadeOuMentira("A estatua de Cristo Redentor está situada na cidade de São Paulo, en Brasil.", 0))
        questions.add(QuestionVerdadeOuMentira("O compositor alemán Johann Sebastian Bach é coñecido pola súa obra 'Sinfonía das Mareas'.", 0))
        questions.add(QuestionVerdadeOuMentira("O lago Baikal, situado en Rusia, é o lago máis profundo do mundo.", 1))
        questions.add(QuestionVerdadeOuMentira("A Gran Muralla China foi construída para protexer o imperio chino de invasións estranxeiras.", 1))
        questions.add(QuestionVerdadeOuMentira("A Mona Lisa é coñecida polo seu sorriso misterioso.", 1))
        questions.add(QuestionVerdadeOuMentira("O primeiro home en chegar ao cume do monte Everest foi Sir Edmund Hillary.", 1))
        questions.add(QuestionVerdadeOuMentira("O sistema solar está composto por oito planetas.", 1))
        questions.add(QuestionVerdadeOuMentira("O actor Morgan Freeman interpretou o papel de Deus na película 'Todo-Poderoso'.", 1))
        questions.add(QuestionVerdadeOuMentira("A fórmula química H2O representa o dióxido de carbono.", 0))
        questions.add(QuestionVerdadeOuMentira("O primeiro presidente dos Estados Unidos foi Thomas Jefferson.", 0))
        questions.add(QuestionVerdadeOuMentira("O alfabeto cirílico é utilizado en idiomas como o ruso e o búlgaro.", 1))
        questions.add(QuestionVerdadeOuMentira("O poema épico 'A Divina Comedia' foi escrito por Dante Alighieri.", 1))
        questions.add(QuestionVerdadeOuMentira("O Sahara é o deserto máis grande de África.", 1))
        questions.add(QuestionVerdadeOuMentira("O pintor renacentista Michelangelo foi tamén un destacado escultor.", 1))
        questions.add(QuestionVerdadeOuMentira("A capital de Australia é Sidney.", 0))
        questions.add(QuestionVerdadeOuMentira("O Rei León é unha película animada producida por Pixar.", 0))
        questions.add(QuestionVerdadeOuMentira("O primeiro voo dos irmáns Wright ocorreu en Kitty Hawk, Carolina do Norte.", 1))
        questions.add(QuestionVerdadeOuMentira("O Papa actual, Francisco, é de orixe italiana.", 0))
        questions.add(QuestionVerdadeOuMentira("O grupo musical británico The Beatles foi formado na década de 1960.", 1))
        questions.add(QuestionVerdadeOuMentira("O escritor colombiano Gabriel García Márquez é coñecido pola súa obra 'Cien años de soledad'.", 1))
        questions.add(QuestionVerdadeOuMentira("A Gran Esfinxe de Gizé está situada na cidade de El Cairo, en Exipto.", 1))
        questions.add(QuestionVerdadeOuMentira("O Monte Vesuvio, que destruíu as cidades de Pompeia e Herculano no ano 79 d.C., está situado en Italia.", 1))
        questions.add(QuestionVerdadeOuMentira("O autor do libro 'Matar un Ruiseñor' é Harper Lee.", 1))
        questions.add(QuestionVerdadeOuMentira("A cidade de Constantinopla, capital do Imperio Bizantino, é hoxe en día a cidade de Estambul, en Turquía.", 1))
        questions.add(QuestionVerdadeOuMentira("O número de Avogadro, unha constante fundamental na química, é aproximadamente 6.022 x 10^23.", 1))
        questions.add(QuestionVerdadeOuMentira("O libro 'Don Quijote', escrito por Miguel de Cervantes, é considerado unha das primeiras novelas modernas.", 1))
        questions.add(QuestionVerdadeOuMentira("O pintor surrealista Salvador Dalí naceu en Francia.", 0))
        questions.add(QuestionVerdadeOuMentira("O elemento químico plutonio foi nomeado en honra ao deus romano Plutón.", 1))
        questions.add(QuestionVerdadeOuMentira("O animal máis rápido do mundo é o guepardo.", 1))
        questions.add(QuestionVerdadeOuMentira("O tratado de paz que puxo fin á Primeira Guerra Mundial foi o Tratado de Versalles.", 1))
        questions.add(QuestionVerdadeOuMentira("A pintura 'A Noite Estrelada' é obra do pintor francés Claude Monet.", 0))
        questions.add(QuestionVerdadeOuMentira("O teorema de Pitágoras establece a relación entre os lados dun triángulo rectángulo.", 1))
        questions.add(QuestionVerdadeOuMentira("O primeiro emperador de Roma foi Julio César.", 0))
        questions.add(QuestionVerdadeOuMentira("O Nobel de Literatura do ano 2020 foi concedido ao escritor norteamericano Philip Roth.", 0))
        questions.add(QuestionVerdadeOuMentira("A ópera 'Carmen', escrita por Georges Bizet, está ambientada en España.", 1))
        questions.add(QuestionVerdadeOuMentira("A Torre de Londres é unha antiga prisión situada na cidade de Manchester.", 0))
        questions.add(QuestionVerdadeOuMentira("O protocolo HTTPS é un protocolo de seguridade utilizado para conexións seguras en internet.", 1))
        questions.add(QuestionVerdadeOuMentira("O científico británico Isaac Newton é coñecido pola súa obra 'Os Elementos'.", 0))
        questions.add(QuestionVerdadeOuMentira("A Revolución Industrial comezou en Inglaterra no século XVII.", 0))
        questions.add(QuestionVerdadeOuMentira("O escultor renacentista Michelangelo foi tamén o arquitecto principal da Catedral de San Pedro, en Roma.", 1))
        return questions
    }
}